-- Native invoicing (Tier 1, Stage 3) -- this app's own invoices table,
-- independent of Jobber. Nothing writes to this yet (createInvoice() in
-- lib/invoices.ts exists but isn't called from any page/action) --
-- Stage 4 adds PDF + Resend delivery, Stage 7 is the actual cutover of
-- app/(platform)/invoices/actions.ts away from createJobberInvoice().
--
-- No tax fields anywhere here -- AZ turf care carries no sales tax
-- (confirmed), so total is simply the sum of line items, full stop. See
-- the Tier 1 scope doc for the reasoning.

-- Sequential, year-scoped invoice numbers (INV-2026-0001, INV-2026-0002,
-- ...) generated by next_invoice_number() below rather than client-side,
-- so concurrent invoice creation can't collide. One row per calendar
-- year; the counter resets naturally each year since a new year gets
-- its own row starting at 1.
create table if not exists invoice_number_counters (
  year integer primary key,
  last_number integer not null default 0
);

-- Atomic under concurrent calls: the ON CONFLICT DO UPDATE branch takes
-- a row lock on the current year's counter row for the duration of the
-- transaction, so two invoices created at the same instant still get
-- distinct sequential numbers.
create or replace function next_invoice_number() returns text as $$
declare
  current_year integer := extract(year from now())::integer;
  next_num integer;
begin
  insert into invoice_number_counters (year, last_number)
  values (current_year, 1)
  on conflict (year) do update
    set last_number = invoice_number_counters.last_number + 1
  returning last_number into next_num;

  return 'INV-' || current_year || '-' || lpad(next_num::text, 4, '0');
end;
$$ language plpgsql;

create table if not exists invoices (
  id uuid primary key default gen_random_uuid(),
  invoice_number text not null unique,
  -- Matches every other table in this app (jobber_visits, jobber_jobs,
  -- jobber_invoices) -- customers are looked up by jobber_client_id
  -- throughout, not a separate uuid FK. Nullable + ON DELETE SET NULL
  -- since customer rows are never hard-deleted in this app (see
  -- handleDestroyedCustomer in lib/jobberWebhookProcessor.ts), but this
  -- stays defensive rather than assuming that never changes.
  jobber_client_id text references customers(jobber_client_id) on delete set null,
  customer_name text,
  status text not null default 'draft'
    check (status in ('draft', 'sent', 'paid', 'overdue', 'void')),
  total numeric(10, 2) not null default 0,
  issue_date date not null default current_date,
  due_date date,
  message text,
  sent_at timestamptz,
  paid_at timestamptz,
  -- Set once a Stripe Checkout session is created for this invoice
  -- (Stage 4+) -- lets the webhook processor (lib/stripeWebhookProcessor.ts)
  -- find the invoice a payment_intent/checkout.session event belongs to.
  stripe_checkout_session_id text,
  created_by_user_id uuid references users(id) on delete set null,
  created_by_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists invoices_jobber_client_id_idx
  on invoices (jobber_client_id);
create index if not exists invoices_status_idx
  on invoices (status);
create index if not exists invoices_stripe_checkout_session_id_idx
  on invoices (stripe_checkout_session_id);

create table if not exists invoice_line_items (
  id uuid primary key default gen_random_uuid(),
  invoice_id uuid not null references invoices(id) on delete cascade,
  description text not null,
  quantity numeric(10, 2) not null default 1,
  unit_price numeric(10, 2) not null,
  line_total numeric(10, 2) not null,
  -- Internal cost (materials + labor), separate from unit_price -- same
  -- passthrough createJobberInvoice() already does today from
  -- visit_material_cost, so job-costing analytics doesn't need to
  -- change once this table is actually used.
  cost numeric(10, 2),
  -- Nullable on purpose (per the Tier 1 scope doc's visit-linkage
  -- decision): a line item can bill a Jobber-synced visit today, a
  -- native visit once Tier 2's own jobs/visits tables exist, or no
  -- visit at all (a one-off charge, a materials-only bill). No FK
  -- constraint to jobber_visits -- Jobber visit IDs aren't guaranteed
  -- to stick around (see handleDestroyedVisit's hard delete), and an
  -- invoice line item is exactly the kind of record that should survive
  -- that regardless.
  jobber_visit_id text,
  created_at timestamptz not null default now()
);

create index if not exists invoice_line_items_invoice_id_idx
  on invoice_line_items (invoice_id);
